// Math puzzles — Tier 1 (age ≤ 8): addition, subtraction, simple patterns
module.exports = [
  {
    id: 'math-t1-001',
    type: 'equation',
    subject: 'math',
    prompt: '3 + 7 = ?',
    options: null,
    answer: '10',
    normalizedAnswer: '10',
    hint: 'Count up from 3 by 7 steps: 4, 5, 6, 7, 8, 9, 10',
    estimatedSeconds: 20,
  },
  {
    id: 'math-t1-002',
    type: 'equation',
    subject: 'math',
    prompt: '12 − 5 = ?',
    options: null,
    answer: '7',
    normalizedAnswer: '7',
    hint: 'Start at 12 and count back 5 steps',
    estimatedSeconds: 20,
  },
  {
    id: 'math-t1-003',
    type: 'multiple_choice',
    subject: 'math',
    prompt: 'What comes next? 2, 4, 6, 8, ___',
    options: ['9', '10', '11', '12'],
    answer: '10',
    normalizedAnswer: '10',
    hint: 'The pattern adds 2 each time',
    estimatedSeconds: 25,
  },
  {
    id: 'math-t1-004',
    type: 'equation',
    subject: 'math',
    prompt: '6 + 8 = ?',
    options: null,
    answer: '14',
    normalizedAnswer: '14',
    hint: '6 + 8 = 6 + 4 + 4 = 10 + 4',
    estimatedSeconds: 20,
  },
  {
    id: 'math-t1-005',
    type: 'equation',
    subject: 'math',
    prompt: '15 − 7 = ?',
    options: null,
    answer: '8',
    normalizedAnswer: '8',
    hint: 'Start at 15 and count back 7',
    estimatedSeconds: 25,
  },
  {
    id: 'math-t1-006',
    type: 'multiple_choice',
    subject: 'math',
    prompt: 'Which shape has 4 equal sides?',
    options: ['Triangle', 'Circle', 'Square', 'Pentagon'],
    answer: 'Square',
    normalizedAnswer: 'square',
    hint: 'Think of a box or a chessboard tile',
    estimatedSeconds: 20,
  },
  {
    id: 'math-t1-007',
    type: 'equation',
    subject: 'math',
    prompt: '4 × 3 = ?',
    options: null,
    answer: '12',
    normalizedAnswer: '12',
    hint: 'Count by 4s three times: 4, 8, 12',
    estimatedSeconds: 25,
  },
  {
    id: 'math-t1-008',
    type: 'multiple_choice',
    subject: 'math',
    prompt: 'What comes next? 5, 10, 15, 20, ___',
    options: ['22', '23', '24', '25'],
    answer: '25',
    normalizedAnswer: '25',
    hint: 'The pattern counts by 5s',
    estimatedSeconds: 20,
  },
  {
    id: 'math-t1-009',
    type: 'equation',
    subject: 'math',
    prompt: '9 + 9 = ?',
    options: null,
    answer: '18',
    normalizedAnswer: '18',
    hint: '9 + 9 = 10 + 8',
    estimatedSeconds: 20,
  },
  {
    id: 'math-t1-010',
    type: 'equation',
    subject: 'math',
    prompt: '20 − 13 = ?',
    options: null,
    answer: '7',
    normalizedAnswer: '7',
    hint: 'What number plus 13 makes 20?',
    estimatedSeconds: 25,
  },
];
