// Math puzzles — Tier 3 (age 13+): algebra, percentages, word problems
module.exports = [
  {
    id: 'math-t3-001',
    type: 'equation',
    subject: 'math',
    prompt: 'Solve for x: 2x + 5 = 17',
    options: null,
    answer: '6',
    normalizedAnswer: '6',
    hint: 'Subtract 5 from both sides first, then divide by 2',
    estimatedSeconds: 45,
  },
  {
    id: 'math-t3-002',
    type: 'equation',
    subject: 'math',
    prompt: 'A store marks up a $40 item by 35%. What is the selling price?',
    options: null,
    answer: '54',
    normalizedAnswer: '54',
    hint: '35% of 40 = 14, so 40 + 14 = ?',
    estimatedSeconds: 50,
  },
  {
    id: 'math-t3-003',
    type: 'equation',
    subject: 'math',
    prompt: 'Solve for x: 3x − 9 = 2x + 4',
    options: null,
    answer: '13',
    normalizedAnswer: '13',
    hint: 'Move all x terms to one side: 3x − 2x = 4 + 9',
    estimatedSeconds: 50,
  },
  {
    id: 'math-t3-004',
    type: 'multiple_choice',
    subject: 'math',
    prompt: 'The average of 5 numbers is 12. What is their sum?',
    options: ['48', '55', '60', '72'],
    answer: '60',
    normalizedAnswer: '60',
    hint: 'Sum = average × count',
    estimatedSeconds: 40,
  },
  {
    id: 'math-t3-005',
    type: 'equation',
    subject: 'math',
    prompt: 'What is 15% of 260?',
    options: null,
    answer: '39',
    normalizedAnswer: '39',
    hint: '10% of 260 = 26, 5% = 13, add them',
    estimatedSeconds: 45,
  },
  {
    id: 'math-t3-006',
    type: 'equation',
    subject: 'math',
    prompt: 'If f(x) = 3x² − 2, what is f(3)?',
    options: null,
    answer: '25',
    normalizedAnswer: '25',
    hint: '3 × (3²) − 2 = 3 × 9 − 2',
    estimatedSeconds: 50,
  },
  {
    id: 'math-t3-007',
    type: 'equation',
    subject: 'math',
    prompt: 'A price drops from $80 to $60. What is the percentage decrease?',
    options: null,
    answer: '25',
    normalizedAnswer: '25',
    hint: 'Change ÷ original × 100. Change = 20, Original = 80',
    estimatedSeconds: 55,
  },
  {
    id: 'math-t3-008',
    type: 'multiple_choice',
    subject: 'math',
    prompt: 'The sum of angles in a triangle is 180°. Two angles are 55° and 72°. What is the third?',
    options: ['43°', '53°', '57°', '63°'],
    answer: '53°',
    normalizedAnswer: '53°',
    hint: '180 − 55 − 72 = ?',
    estimatedSeconds: 40,
  },
  {
    id: 'math-t3-009',
    type: 'equation',
    subject: 'math',
    prompt: 'Solve: 4(x − 3) = 2(x + 5)',
    options: null,
    answer: '11',
    normalizedAnswer: '11',
    hint: 'Expand both sides: 4x − 12 = 2x + 10, then solve',
    estimatedSeconds: 55,
  },
  {
    id: 'math-t3-010',
    type: 'equation',
    subject: 'math',
    prompt: 'A car travels 240 km using 16 litres of fuel. How many km per litre?',
    options: null,
    answer: '15',
    normalizedAnswer: '15',
    hint: 'Divide total distance by total fuel used',
    estimatedSeconds: 40,
  },
];
