// Math puzzles — Tier 2 (age 9–12): multiplication, division, fractions, geometry
module.exports = [
  {
    id: 'math-t2-001',
    type: 'equation',
    subject: 'math',
    prompt: '144 ÷ 12 = ?',
    options: null,
    answer: '12',
    normalizedAnswer: '12',
    hint: '12 × 12 = 144',
    estimatedSeconds: 35,
  },
  {
    id: 'math-t2-002',
    type: 'equation',
    subject: 'math',
    prompt: '1/2 + 1/4 = ? (write as a fraction, e.g. 3/4)',
    options: null,
    answer: '3/4',
    normalizedAnswer: '3/4',
    hint: 'Convert 1/2 to 2/4, then add',
    estimatedSeconds: 40,
  },
  {
    id: 'math-t2-003',
    type: 'equation',
    subject: 'math',
    prompt: 'What is the area of a rectangle 6 cm wide and 9 cm tall?',
    options: null,
    answer: '54',
    normalizedAnswer: '54',
    hint: 'Area = width × height',
    estimatedSeconds: 35,
  },
  {
    id: 'math-t2-004',
    type: 'multiple_choice',
    subject: 'math',
    prompt: '25% of 80 = ?',
    options: ['15', '20', '25', '30'],
    answer: '20',
    normalizedAnswer: '20',
    hint: '25% means one quarter. 80 ÷ 4 = ?',
    estimatedSeconds: 35,
  },
  {
    id: 'math-t2-005',
    type: 'equation',
    subject: 'math',
    prompt: '7 × 8 = ?',
    options: null,
    answer: '56',
    normalizedAnswer: '56',
    hint: '7 × 8 = 7 × 4 × 2 = 28 × 2',
    estimatedSeconds: 25,
  },
  {
    id: 'math-t2-006',
    type: 'equation',
    subject: 'math',
    prompt: '256 ÷ 8 = ?',
    options: null,
    answer: '32',
    normalizedAnswer: '32',
    hint: '8 × 30 = 240, 256 − 240 = 16, 16 ÷ 8 = 2, so 30 + 2 = 32',
    estimatedSeconds: 40,
  },
  {
    id: 'math-t2-007',
    type: 'multiple_choice',
    subject: 'math',
    prompt: 'What is the perimeter of a square with side 7 cm?',
    options: ['14 cm', '21 cm', '28 cm', '49 cm'],
    answer: '28 cm',
    normalizedAnswer: '28cm',
    hint: 'Perimeter = 4 × side',
    estimatedSeconds: 30,
  },
  {
    id: 'math-t2-008',
    type: 'equation',
    subject: 'math',
    prompt: '3/5 of 45 = ?',
    options: null,
    answer: '27',
    normalizedAnswer: '27',
    hint: '45 ÷ 5 = 9, then 9 × 3 = 27',
    estimatedSeconds: 40,
  },
  {
    id: 'math-t2-009',
    type: 'multiple_choice',
    subject: 'math',
    prompt: 'A train travels 60 km/h for 2.5 hours. How far does it go?',
    options: ['120 km', '135 km', '150 km', '160 km'],
    answer: '150 km',
    normalizedAnswer: '150km',
    hint: 'Distance = speed × time',
    estimatedSeconds: 45,
  },
  {
    id: 'math-t2-010',
    type: 'equation',
    subject: 'math',
    prompt: 'What is the value of 2³ (2 to the power of 3)?',
    options: null,
    answer: '8',
    normalizedAnswer: '8',
    hint: '2³ = 2 × 2 × 2',
    estimatedSeconds: 30,
  },
];
